# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Popularinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop', models.TextField(db_column='Shop')),
                ('prodname', models.TextField(db_column='ProdName')),
                ('price', models.CharField(db_column='Price', max_length=10)),
                ('shipfee', models.CharField(blank=True, db_column='ShipFee', max_length=10, null=True)),
                ('shorturl', models.CharField(db_column='ShortUrl', max_length=30)),
                ('popular', models.IntegerField(db_column='Popular')),
                ('inputtime', models.CharField(db_column='InputTime', max_length=6)),
                ('inputdate', models.CharField(db_column='InputDate', max_length=8)),
            ],
            options={
                'db_table': 'PopularInfo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Searchinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(blank=True, db_column='UserID', max_length=33, null=True)),
                ('username', models.CharField(blank=True, db_column='UserName', max_length=50, null=True)),
                ('keyword', models.CharField(blank=True, db_column='KeyWord', max_length=50, null=True)),
                ('miniprice', models.DecimalField(blank=True, db_column='MiniPrice', decimal_places=0, max_digits=18, null=True)),
                ('exceptword', models.CharField(blank=True, db_column='ExceptWord', max_length=50, null=True)),
                ('inputtime', models.CharField(blank=True, db_column='InputTime', max_length=8, null=True)),
                ('inputdate', models.CharField(blank=True, db_column='InputDate', max_length=8, null=True)),
            ],
            options={
                'db_table': 'SearchInfo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=10)),
                ('channel', models.IntegerField(db_column='Channel')),
                ('uid', models.TextField()),
            ],
            options={
                'db_table': 'UserInfo',
                'managed': True,
            },
        ),
    ]
